name: padder
description: Simple padding widgets for Flutter
version: 1.2.0
author: Josh Burton <athor3d@gmail.com>
homepage: https://github.com/arklabsnz/Padder

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
